/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.transport;

import org.mule.DefaultMuleEvent;
import org.mule.DefaultMuleMessage;
import org.mule.MessageExchangePattern;
import org.mule.api.*;
import org.mule.api.annotations.*;
import org.mule.api.annotations.lifecycle.Start;
import org.mule.api.annotations.param.ConnectionKey;
import org.mule.api.annotations.param.Optional;
import org.mule.api.annotations.param.Payload;
import org.mule.api.callback.SourceCallback;
import org.mule.api.construct.FlowConstruct;
import org.mule.api.processor.MessageProcessor;
import org.mule.session.DefaultMuleSession;
import org.mule.transformer.simple.ObjectToByteArray;
import org.mule.transport.sources.InboundEndpointMessageSource;
import org.zeromq.ZMQ;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import java.io.ByteArrayOutputStream;
import java.io.ObjectOutputStream;
import java.lang.reflect.Field;

/**
 * ZeroMQ Transport
 *
 * @author Claude
 */
@Connector(name = "zeromq", schemaVersion = "1.0-SNAPSHOT")
public class ZeroMQTransport {

    public enum ExchangePattern {
        REQUEST_RESPONSE, ONE_WAY, PUBLISH, SUBSCRIBE, PUSH, PULL
    }

    public enum SocketOperation {
        BIND, CONNECT
    }

    private ZMQ.Context zmqContext;
    private ZMQ.Socket zmqSocket;
    private SocketOperation socketOperation;
    private String address;
    private String filter;
    private ExchangePattern exchangePattern;
    private ObjectToByteArray objectToByteArray;

    /**
     * Connect
     *
     * @param exchangePattern A password
     * @param socketOperation A username
     * @param address         A password
     * @param filter          A password
     * @throws ConnectionException
     */
    @Connect
    public void connect(@ConnectionKey ExchangePattern exchangePattern, @ConnectionKey SocketOperation socketOperation, @ConnectionKey String address,  @ConnectionKey String filter, boolean isInbound)
            throws ConnectionException {

        if (!isInbound) {
            this.exchangePattern = exchangePattern;
            this.socketOperation = socketOperation;
            this.address = address;
            this.filter = filter;

            switch (exchangePattern) {
                case REQUEST_RESPONSE:
                    zmqSocket = requestResponseSender(socketOperation, address);
                    break;
                case PUBLISH:
                    zmqSocket = publish(socketOperation, address);
                    break;
                case ONE_WAY:
                    zmqSocket = requestResponseSender(socketOperation, address);
                    break;
                case SUBSCRIBE:
                    zmqSocket = subscribe(socketOperation, address, filter);
                    break;
            }
        }
    }

    @Start
    public void initialise() {
        zmqContext = ZMQ.context(1);
        objectToByteArray = new ObjectToByteArray();
    }

    @PreDestroy
    public void destroy() {
        zmqContext.term();
    }

    /**
     * Disconnect
     */
    @Disconnect
    public void disconnect() {
        zmqSocket.close();
    }

    /**
     * Are we connected
     */
    @ValidateConnection
    public boolean isConnected() {
        if (zmqSocket != null)
            return true;
        else
            return false;
    }

    /**
     * Are we connected
     */
    @ConnectionIdentifier
    public String connectionId() {
        return "001";
    }

    /**
     * Custom processor
     * <p/>
     * {@sample.xml ../../../doc/zeromq-connector.xml.sample zeromq:outbound-endpoint}
     *
     * @param payload Content to be processed
     * @return Some string
     */
    @Processor
    public byte[] outboundEndpoint(@Payload byte[] payload) throws Exception {
        byte[] message;

        switch (exchangePattern) {
            case REQUEST_RESPONSE:
                zmqSocket.send(payload, 0);
                message = zmqSocket.recv(0);
                break;
            case PUBLISH:
                zmqSocket.send(payload, 0);
                message = payload;
                break;
            case ONE_WAY:
                zmqSocket.send(payload, 0);
                message = payload;
                break;
            case SUBSCRIBE:
                message = zmqSocket.recv(0);
                break;
            default:
                throw new UnsupportedOperationException();
        }

        return message;
    }

    /**
     * Custom processor
     * <p/>
     * {@sample.xml ../../../doc/zeromq-connector.xml.sample zeromq:outbound-endpoint}
     *
     * @param exchangePattern2 Content to be processed
     * @param socketOperation2 Content to be processed
     * @param address2         Content to be processed
     * @param filter2          Content to be processed
     * @param callback         Content to be processed
     */
    @Source
    public void inboundEndpoint(ExchangePattern exchangePattern, SocketOperation socketOperation, String address, @Optional String filter, SourceCallback callback) throws Exception {
        byte[] message = null;

        switch (exchangePattern) {

            case REQUEST_RESPONSE:
                zmqSocket = requestResponseReceiver(socketOperation, address);
                message = zmqSocket.recv(0);
                Object response = callback.process(message);
                zmqSocket.send((byte[]) objectToByteArray.transform(response), 0);
                break;

            case ONE_WAY:
                zmqSocket = requestResponseReceiver(socketOperation, address);
                message = zmqSocket.recv(0);
                callback.process(message);
                break;

            case SUBSCRIBE:
                zmqSocket = subscribe(socketOperation, address, filter);
                message = zmqSocket.recv(0);
                callback.process(message);
                break;

            case PUBLISH:
                throw new UnsupportedOperationException();

            case PUSH:
                throw new UnsupportedOperationException();

            case PULL:
                zmqSocket = pull(socketOperation, address);
                message = zmqSocket.recv(0);
                callback.process(message);
                break;
        }
    }

    private ZMQ.Socket subscribe(SocketOperation socketOperation, String address, String filter) {
        ZMQ.Socket zmqSocket = zmqContext.socket(ZMQ.SUB);

        prepare(zmqSocket, socketOperation, address);

        if (filter != null) {
            zmqSocket.subscribe(filter.getBytes());
        } else {
            zmqSocket.subscribe(new byte[]{});
        }

        return zmqSocket;
    }

    private ZMQ.Socket pull(SocketOperation socketOperation, String address) {
        ZMQ.Socket zmqSocket = zmqContext.socket(ZMQ.PULL);
        prepare(zmqSocket, socketOperation, address);

        return zmqSocket;
    }

    private ZMQ.Socket requestResponseReceiver(SocketOperation socketOperation, String address) {
        ZMQ.Socket zmqSocket = zmqContext.socket(ZMQ.REP);
        prepare(zmqSocket, socketOperation, address);

        return zmqSocket;
    }

    private ZMQ.Socket requestResponseSender(SocketOperation socketOperation, String address) {
        ZMQ.Socket zmqSocket = zmqContext.socket(ZMQ.REQ);
        prepare(zmqSocket, socketOperation, address);

        return zmqSocket;
    }

    private ZMQ.Socket publish(SocketOperation socketOperation, String address) {
        ZMQ.Socket zmqSocket = zmqContext.socket(ZMQ.PUB);
        String[] subscribers = address.split(";");

        for (String subscriber : subscribers) {
            prepare(zmqSocket, socketOperation, subscriber);
        }

        return zmqSocket;
    }

    private void prepare(ZMQ.Socket zmqSocket, SocketOperation socketOperation, String address) {
        if (socketOperation.equals(SocketOperation.BIND)) {
            zmqSocket.bind(address);
        } else {
            zmqSocket.connect(address);
        }
    }

}
