
package org.mule.transport.sources;

import org.mule.DefaultMuleEvent;
import org.mule.DefaultMuleMessage;
import org.mule.MessageExchangePattern;
import org.mule.RequestContext;
import org.mule.api.*;
import org.mule.api.callback.SourceCallback;
import org.mule.api.construct.FlowConstruct;
import org.mule.api.construct.FlowConstructAware;
import org.mule.api.context.MuleContextAware;
import org.mule.api.lifecycle.Initialisable;
import org.mule.api.lifecycle.InitialisationException;
import org.mule.api.lifecycle.Startable;
import org.mule.api.lifecycle.Stoppable;
import org.mule.api.processor.MessageProcessor;
import org.mule.api.registry.RegistrationException;
import org.mule.api.source.MessageSource;
import org.mule.api.transformer.DataType;
import org.mule.api.transformer.Transformer;
import org.mule.config.i18n.CoreMessages;
import org.mule.config.i18n.MessageFactory;
import org.mule.session.DefaultMuleSession;
import org.mule.transformer.types.DataTypeFactory;
import org.mule.transport.ZeroMQTransport;
import org.mule.transport.adapters.ZeroMQTransportConnectionManager;
import org.mule.transport.adapters.ZeroMQTransportLifecycleAdapter;

import java.util.Map;


/**
 * InboundEndpointMessageSource wraps {@link org.mule.transport.ZeroMQTransport#inboundEndpoint(org.mule.transport.ZeroMQTransport.ExchangePattern, org.mule.transport.ZeroMQTransport.SocketOperation, String, String, org.mule.api.callback.SourceCallback)} method in {@link org.mule.transport.ZeroMQTransport } as a message source capable of generating Mule events.  The POJO's method is invoked in its own thread.
 *
 */
public class InboundEndpointMessageSource
    implements Runnable, SourceCallback, FlowConstructAware, MuleContextAware, Initialisable, Startable, Stoppable, MessageSource
{

    private Object exchangePattern;
    private ZeroMQTransport.ExchangePattern _exchangePatternType;
    private Object socketOperation;
    private ZeroMQTransport.SocketOperation _socketOperationType;
    private Object address;
    private String _addressType;
    private Object filter;
    private String _filterType;
    private ZeroMQTransport.ExchangePattern transformedExchangePattern;

    /**
     * Module object
     *
     */
    private Object moduleObject;
    /**
     * Mule Context
     *
     */
    private MuleContext muleContext;
    /**
     * Flow construct
     *
     */
    private FlowConstruct flowConstruct;
    /**
     * Message processor that will get called for processing incoming events
     *
     */
    private MessageProcessor messageProcessor;
    /**
     * Thread under which this message source will execute
     *
     */
    private Thread thread;

    /**
     * Obtains the expression manager from the Mule context and initialises the connector. If a target object  has not been set already it will search the Mule registry for a default one.
     *
     * @throws org.mule.api.lifecycle.InitialisationException
     */
    public void initialise()
        throws InitialisationException
    {
        if (moduleObject == null) {
            try {
                moduleObject = muleContext.getRegistry().lookupObject(ZeroMQTransportConnectionManager.class);
                if (moduleObject == null) {
                    moduleObject = new ZeroMQTransportConnectionManager();
                    muleContext.getRegistry().registerObject(ZeroMQTransportConnectionManager.class.getName(), moduleObject);
                }
            } catch (RegistrationException e) {
                throw new InitialisationException(CoreMessages.initialisationFailure("org.mule.transport.adapters.ZeroMQTransportConnectionManager"), e, this);
            }
        }
        if (moduleObject instanceof String) {
            moduleObject = muleContext.getRegistry().lookupObject(((String) moduleObject));
            if (moduleObject == null) {
                throw new InitialisationException(MessageFactory.createStaticMessage("Cannot find object by config name"), this);
            }
        }
    }

    /**
     * Set the Mule context
     *
     * @param context Mule context to set
     */
    public void setMuleContext(MuleContext context) {
        this.muleContext = context;
    }

    /**
     * Sets the instance of the object under which the processor will execute
     *
     * @param moduleObject Instace of the module
     */
    public void setModuleObject(Object moduleObject) {
        this.moduleObject = moduleObject;
    }

    /**
     * Sets the message processor that will "listen" the events generated by this message source
     *
     * @param listener Message processor
     */
    public void setListener(MessageProcessor listener) {
        this.messageProcessor = listener;
    }

    /**
     * Sets flow construct
     *
     * @param flowConstruct Flow construct to set
     */
    public void setFlowConstruct(FlowConstruct flowConstruct) {
        this.flowConstruct = flowConstruct;
    }

    /**
     * Sets socketOperation
     *
     * @param value Value to set
     */
    public void setSocketOperation(Object value) {
        this.socketOperation = value;
    }

    /**
     * Sets address
     *
     * @param value Value to set
     */
    public void setAddress(Object value) {
        this.address = value;
    }

    /**
     * Sets exchangePattern
     *
     * @param value Value to set
     */
    public void setExchangePattern(Object value) {
        this.exchangePattern = value;
    }

    /**
     * Sets filter
     *
     * @param value Value to set
     */
    public void setFilter(Object value) {
        this.filter = value;
    }

    /**
     * Implements {@link org.mule.api.callback.SourceCallback#process(org.mule.api.MuleEvent)}. This message source will be passed on to the actual pojo's method as a callback mechanism.
     *
     */
    public Object process(Object message)
        throws Exception
    {
        MuleMessage muleMessage;
        muleMessage = new DefaultMuleMessage(message, muleContext);
        MuleSession muleSession;
        muleSession = new DefaultMuleSession(flowConstruct, muleContext);
        MuleEvent muleEvent;
        if (transformedExchangePattern.equals(ZeroMQTransport.ExchangePattern.REQUEST_RESPONSE))
        {
            muleEvent = new DefaultMuleEvent(muleMessage, MessageExchangePattern.REQUEST_RESPONSE, muleSession);
        }
        else {
            muleEvent = new DefaultMuleEvent(muleMessage, MessageExchangePattern.ONE_WAY, muleSession);
        }

        try {
            MuleEvent responseEvent;
            responseEvent = messageProcessor.process(muleEvent);
            if ((responseEvent!= null)&&(responseEvent.getMessage()!= null)) {
                return responseEvent.getMessage().getPayload();
            }
        } catch (Exception e) {
            throw e;
        }
        return null;
    }

    /**
     * Implements {@link org.mule.api.callback.SourceCallback#process(org.mule.api.MuleEvent)}. This message source will be passed on to the actual pojo's method as a callback mechanism.
     *
     */
    public Object process(Object message, Map<String, Object> properties)
        throws Exception
    {
        MuleMessage muleMessage;
        muleMessage = new DefaultMuleMessage(message, properties, null, null, muleContext);
        MuleSession muleSession;
        muleSession = new DefaultMuleSession(flowConstruct, muleContext);
        MuleEvent muleEvent;
        muleEvent = new DefaultMuleEvent(muleMessage, MessageExchangePattern.ONE_WAY, muleSession);
        try {
            MuleEvent responseEvent;
            responseEvent = messageProcessor.process(muleEvent);
            if ((responseEvent!= null)&&(responseEvent.getMessage()!= null)) {
                return responseEvent.getMessage().getPayload();
            }
        } catch (Exception e) {
            throw e;
        }
        return null;
    }

    /**
     * Implements {@link org.mule.api.callback.SourceCallback#process()}. This message source will be passed on to the actual pojo's method as a callback mechanism.
     *
     */
    public Object process()
        throws Exception
    {
        try {
            MuleEvent responseEvent;
            responseEvent = messageProcessor.process(RequestContext.getEvent());
            if ((responseEvent!= null)&&(responseEvent.getMessage()!= null)) {
                return responseEvent.getMessage().getPayload();
            }
        } catch (Exception e) {
            throw e;
        }
        return null;
    }

    /**
     * Method to be called when Mule instance gets started.
     *
     */
    public void start()
        throws MuleException
    {
        if (thread == null) {
            thread = new Thread(this, "Receiving Thread");
        }
        thread.start();
    }

    /**
     * Method to be called when Mule instance gets stopped.
     *
     */
    public void stop()
        throws MuleException
    {
        thread.interrupt();
    }

    /**
     * Implementation {@link Runnable#run()} that will invoke the method on the pojo that this message source wraps.
     *
     */
    public void run() {
        ZeroMQTransportConnectionManager castedModuleObject = null;
        ZeroMQTransportLifecycleAdapter connection = null;
        ZeroMQTransport.SocketOperation transformedSocketOperation = null;
        String transformedAddress = null;
        String transformedFilter = null;
        try {
            if (moduleObject instanceof String) {
                castedModuleObject = ((ZeroMQTransportConnectionManager) muleContext.getRegistry().lookupObject(((String) moduleObject)));
                if (castedModuleObject == null) {
                    throw new MessagingException(CoreMessages.failedToCreate("inboundEndpoint"), ((MuleEvent) null), new RuntimeException("Cannot find the configuration specified by the config-ref attribute."));
                }
            } else {
                castedModuleObject = ((ZeroMQTransportConnectionManager) moduleObject);
            }

            if (exchangePattern != null) {
                if (!ZeroMQTransport.ExchangePattern.class.isAssignableFrom(exchangePattern.getClass())) {
                    DataType source;
                    DataType target;
                    source = DataTypeFactory.create(exchangePattern.getClass());
                    target = DataTypeFactory.create(ZeroMQTransport.ExchangePattern.class);
                    Transformer t;
                    t = muleContext.getRegistry().lookupTransformer(source, target);
                    transformedExchangePattern = ((ZeroMQTransport.ExchangePattern) t.transform(exchangePattern));
                } else {
                    transformedExchangePattern = ((ZeroMQTransport.ExchangePattern) exchangePattern);
                }
            }

            if (socketOperation != null) {
                if (!ZeroMQTransport.SocketOperation.class.isAssignableFrom(socketOperation.getClass())) {
                    DataType source;
                    DataType target;
                    source = DataTypeFactory.create(socketOperation.getClass());
                    target = DataTypeFactory.create(ZeroMQTransport.SocketOperation.class);
                    Transformer t;
                    t = muleContext.getRegistry().lookupTransformer(source, target);
                    transformedSocketOperation = ((ZeroMQTransport.SocketOperation) t.transform(socketOperation));
                } else {
                    transformedSocketOperation = ((ZeroMQTransport.SocketOperation) socketOperation);
                }
            }

            if (address != null) {
                if (!String.class.isAssignableFrom(address.getClass())) {
                    DataType source;
                    DataType target;
                    source = DataTypeFactory.create(address.getClass());
                    target = DataTypeFactory.create(String.class);
                    Transformer t;
                    t = muleContext.getRegistry().lookupTransformer(source, target);
                    transformedAddress = ((String) t.transform(address));
                } else {
                    transformedAddress = ((String) address);
                }
            }

            if (filter != null) {
                if (!String.class.isAssignableFrom(filter.getClass())) {
                    DataType source;
                    DataType target;
                    source = DataTypeFactory.create(filter.getClass());
                    target = DataTypeFactory.create(String.class);
                    Transformer t;
                    t = muleContext.getRegistry().lookupTransformer(source, target);
                    transformedFilter = ((String) t.transform(filter));
                } else {
                    transformedFilter = ((String) filter);
                }
            }
            connection = castedModuleObject.acquireConnection(new ZeroMQTransportConnectionManager.ConnectionKey(transformedExchangePattern, transformedSocketOperation, transformedAddress, transformedFilter, true));
            if (connection == null) {
                throw new MessagingException(CoreMessages.failedToCreate("inboundEndpoint"), ((MuleEvent) null), new RuntimeException("Cannot create connection"));
            }
            connection.inboundEndpoint(transformedExchangePattern, transformedSocketOperation, transformedAddress, transformedFilter, this);
        } catch (MessagingException e) {
            flowConstruct.getExceptionListener().handleException(e, e.getEvent());
        } catch (Exception e) {
            muleContext.getExceptionListener().handleException(e);
        } finally {
            if (connection!= null) {
                try {
                    castedModuleObject.releaseConnection(new ZeroMQTransportConnectionManager.ConnectionKey(transformedExchangePattern, transformedSocketOperation, transformedAddress, transformedFilter, false), connection);
                } catch (Exception _x) {
                }
            }
        }
    }

}
